### ISSUE TITLE
有没有交流解答群

### ISSUE THREAD

**Issue by checkchen6** [NaiveSteven/ideaz-element#156]
有没有交流解答群

**Comment by checkchen6** [comment]
const formConfig = ref({
  columns: [
    {
      component: 'input',
      field: 'name',
      label: '姓名2222222222222',
      labelWidth: '200px',
      required: true,
    },
这里的labelWidth属性不生效

**Comment by NaiveSteven** [comment]
labelWidth目前暂不支持直接和label同一层级，您可以先放到fieldProps对象中，我后续会兼容

**Comment by NaiveSteven** [comment]
labelWidth目前暂不支持直接和label同一层级，您可以先放到formItemProps对象中，我后续会兼容
