### ISSUE TITLE
这个submit的params都是undefind

### ISSUE THREAD

**Issue by checkchen6** [NaiveSteven/ideaz-element#157]
![image](https://github.com/user-attachments/assets/03c7bf5a-2eb9-4023-8635-43d515b5bcbf)

**Comment by NaiveSteven** [comment]
不好意思，文档没写清楚，点击确认弹窗默认关闭会清空表单数据，所以打印出来的都是undefined，方法内部正常使用是没问题的。后面会优化下文档。

**Comment by checkchen6** [comment]
感谢解答，有个疑问如下图
![image](https://github.com/user-attachments/assets/68b73aed-d92c-4850-af97-ef4828bf17af)

**Comment by NaiveSteven** [comment]
console.log打印的是最终结果，commonApi调用的时候params还是有值的，点击确认弹窗默认关闭会清空表单数据，所以变成undefined了，您可以在项目中打个断点试一下

**Comment by NaiveSteven** [comment]
这边commonApi就是模仿真实业务中的封装的后端接口，直接将commonApi替换成业务中封装的接口就行

**Comment by checkchen6** [comment]
好的，了解了，晚点我试试，感谢解答
