### ISSUE TITLE
有没有考虑将form和table结合起来呢？

### ISSUE THREAD

**Issue by XM-zombie** [NaiveSteven/ideaz-element#160]

**Comment by NaiveSteven** [comment]
您好，目前有两种方式配置form的table：

1. 在form的column项中类似表单项配置，component传入`z-table`，其他配置参考如下：

**注意：这种情况下，columns需要computed包裹**

![image](https://github.com/user-attachments/assets/98818b49-5692-455f-aa24-02c97efaf825)
![image](https://github.com/user-attachments/assets/3a6826b7-612b-41f9-aca7-ca7250da38de)

后续我会补充文档，添加示例。

2. form的column项配置slot或render函数，这种方式支持任意自定义配置，缺点是模板代码都得自己写

**Comment by XM-zombie** [comment]
wc，兄弟这库很nice

**Comment by XM-zombie** [comment]
有个场景、如果查询条件很多、有没有想过做展开、收起、自适应呢？

**Comment by NaiveSteven** [comment]
您说的是纯表单吗？我不知道这种满不满足您的需求。会根据屏幕大小自定义布局。
![image](https://github.com/user-attachments/assets/5570ade4-218e-4e6c-87a5-92db970857d9)
![image](https://github.com/user-attachments/assets/e1c3d946-949e-4c54-928b-ad5c5c22e947)


表单表格筛选是默认内置了自适应的布局，表单布局固定为{ xs: 24, sm: 12, md: 8, lg: 8, xl: 6 }。
展开、收起需要手动控制。

![image](https://github.com/user-attachments/assets/67544b57-63c8-4d6e-b383-bc0857156f38)
![image](https://github.com/user-attachments/assets/c3fa15a5-e528-4713-95c4-70a7ead0e9c3)
![image](https://github.com/user-attachments/assets/283baabc-beec-48a2-a0f4-eee03e44408c)

**Comment by XM-zombie** [comment]
wc、谢谢大佬、大佬生5个儿子
