### ISSUE TITLE
1、crud组件中form支持自定义顺序吗？2、crud中某个字段只查询、不在列表展示、如何配置

### ISSUE THREAD

**Issue by XM-zombie** [NaiveSteven/ideaz-element#164]

**Comment by NaiveSteven** [comment]
1、form的顺序就是您在columns中配置的顺序，暂不支持额外配置
2、不传prop、slot、render等字段，再额外配置search、form等配置查询表单的字段即可
![image](https://github.com/user-attachments/assets/b7117df2-b7d3-4af9-b384-eff7b3b6ec07)
![image](https://github.com/user-attachments/assets/87404898-a34c-4065-95f9-97a6faf4ac74)

**Comment by XM-zombie** [comment]
那有没有计划开放一个属性、自定义排序呢？

**Comment by NaiveSteven** [comment]
计划最快这两天，最晚这周会发布
