### ISSUE TITLE
表格没有，树形数据

### ISSUE THREAD

**Issue by zhuchunzhou** [NaiveSteven/ideaz-element#169]
表格不支持树类型的数据的显示

![image](https://github.com/user-attachments/assets/58bd2145-4fbe-4370-b8bb-50386185b727)

**Comment by NaiveSteven** [comment]
我试了下，支持树型结构（element-plus的组件属性直接按照element-plus的文档要求传递即可）。您可以将您的代码截图，我帮您看看。
![image](https://github.com/user-attachments/assets/5ba69c7e-b477-4512-9c11-0e76e1d13385)
![image](https://github.com/user-attachments/assets/b381b3c4-1de5-4075-b505-849e0d7d4be7)

**Comment by zhuchunzhou** [comment]
是支持的，不好意思
