### ISSUE TITLE
git clone项目执行 pnpm dev3 提示 'cl' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by zettle** [NaiveSteven/ideaz-element#172]
```shell
pnpm i
pnpm dev3
```
运行项目，提示'cl' 不是内部或外部命令，也不是可运行的程序，是需要全局安装个什么包吗

**Comment by NaiveSteven** [comment]
这个命令现在应该暂时不需要了，如果您要运行项目的话，执行`pnpm docs:dev`即可。

感谢您的提醒，我后续会把执行命令优化下，补充下开发文档
