### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by huanghu0** [NaiveSteven/ideaz-element#174]
when i run npm run build having the error
/
![微信图片_20240918144854](https://github.com/user-attachments/assets/928ca1ae-01c0-4f87-96de-a1d8d586ffa3)

**Comment by NaiveSteven** [comment]
What is your node version and npm version, I recommend using pnpm to manage dependencies

**Comment by NaiveSteven** [comment]
I recommend using at least version 18.x or 20.x of node

**Comment by huanghu0** [comment]
i use pnpm ，my pnpm version is 9.X , and node version is 18.x
![微信图片_20240918171243](https://github.com/user-attachments/assets/00e729c1-34fd-4c35-8570-4a32f0a9e0c5)
![微信图片_20240918171316](https://github.com/user-attachments/assets/6d9b1755-956a-49fe-a0f4-8265bb038ea5)

**Comment by NaiveSteven** [comment]
I tried it locally and couldn't repeat your problem. Maybe you can delete node_modules and clear the cache, reinstall dependencies, or try to install a later version of node
